name: Build and Push Docker Image
on:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: docker/setup-buildx-action@master
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@master
      with:
        tags: |
          pwncollege/pwncollege_challenge:latest
          docker.pkg.github.com/pwncollege/pwncollege/pwncollege_challenge:latest
        file: containers/pwncollege_challenge/Dockerfile
        context: containers/pwncollege_challenge
        push: true
        cache-from: type=registry,ref=docker.pkg.github.com/pwncollege/pwncollege/pwncollege_challenge:latest
        cache-to: type=inline
